### PR TITLE
jupyter-js-services

### PR DESCRIPTION
**Pull request by gnestor**
* Switched from jupyter-kernel-launcher to jupyter-js-services
* Switched from iPython server to Jupyter Kernel Gateway
* Added keymap and menu commands
* Updated style to match native UI and syntax themes
* Fixed issue with process.env.PATH so that it can spawn child processes without requiring Atom to be launched from the command line
* Fixed issue with receiving Jupyter stream/async messages

### CODE REVIEW

**Comment by rgbkrk** [comment]
Well this is awesome. Thank you @gnestor!

**Comment by rgbkrk** [comment]
I'm glad you're using the kernel gateway here too. /cc @parente

**Comment by rgbkrk** [comment]
I'm going to go ahead and merge this so you can shipit and iterate freely. This hasn't been touched in a while; it's good to have you.

**Comment by gnestor** [comment]
@rgbkrk Happy to help. Thanks for adding me to the repo. More to come...

**Pull request merged**
